PREFIX cur: <http://vocabularies.wikipathways.org/wp#Curation:>
prefix dc:      <http://purl.org/dc/elements/1.1/>
prefix dcterms: <http://purl.org/dc/terms/>
prefix foaf:    <http://xmlns.com/foaf/0.1/>
prefix gpml:    <http://vocabularies.wikipathways.org/gpml#>
prefix wp:      <http://vocabularies.wikipathways.org/wp#>
prefix xsd:     <http://www.w3.org/2001/XMLSchema#>

SELECT ?pathway ?license WHERE {
  ?wp wp:isAbout / gpml:license ?license ;
      foaf:page ?pathway .
  MINUS { ?wp wp:ontologyTag cur:Homology_Converted }
} ORDER BY ASC(?wp)
