prefix rdfs:    <http://www.w3.org/2000/01/rdf-schema#>
prefix dc:      <http://purl.org/dc/elements/1.1/>
prefix dcterms: <http://purl.org/dc/terms/>
prefix xsd:     <http://www.w3.org/2001/XMLSchema#>
prefix wp:      <http://vocabularies.wikipathways.org/wp#>
prefix gpml:    <http://vocabularies.wikipathways.org/gpml#>
prefix foaf:    <http://xmlns.com/foaf/0.1/>

SELECT DISTINCT ?homepage (STR(?labelLit) AS ?label) (STR(?idLit) AS ?id) WHERE {
  ?point dcterms:isPartOf ?gpmlpathway ;
               gpml:graphRef ?idLit ;
         dcterms:isPartOf ?interaction .
  ?interaction a gpml:Interaction .
  ?labelNode gpml:textlabel ?labelLit ;
             gpml:graphId ?idLit .
  ?gpmlpathway gpml:hasLabel ?labelNode .
  ?wppathway a wp:Pathway ;
             wp:isAbout ?gpmlpathway  ;
             foaf:page ?homepage .
}
