prefix wp:      <http://vocabularies.wikipathways.org/wp#>
prefix dcterms: <http://purl.org/dc/terms/>
prefix foaf:    <http://xmlns.com/foaf/0.1/>

select (str(?organismName) as ?organism) ?page ?gene ?protein ?interaction where {
  ?interaction wp:source ?gene ;
    wp:target ?protein ;
    a wp:Conversion ;
    dcterms:isPartOf/foaf:page ?pathway ;
    dcterms:isPartOf/wp:organismName ?organismName .
  FILTER (?gene != ?protein)
  FILTER EXISTS {?gene a wp:GeneProduct}
  FILTER EXISTS {?protein a wp:Protein}
} ORDER BY ASC(?organism)
