select (str(?organismName) as ?organism) ?page ?gene ?protein ?interaction where {
  ?gene a wp:GeneProduct .
  ?protein a wp:Protein .
  ?interaction wp:participants ?gene, ?protein ;
    a wp:Interaction, wp:Conversion ;
    dcterms:isPartOf ?pathway .
  ?pathway foaf:page ?page ;
    wp:organismName ?organismName .
  FILTER (?gene != ?protein)
} ORDER BY ASC(?organism) ASC(?pathway)
