prefix wp:      <http://vocabularies.wikipathways.org/wp#>
prefix dcterms: <http://purl.org/dc/terms/>
prefix foaf:    <http://xmlns.com/foaf/0.1/>

select (str(?organismName) as ?organism) ?page ?protein1 ?protein2 ?interaction where {
  ?interaction wp:source ?protein1 ;
    wp:target ?protein2 ;
    a wp:Conversion ;
    dcterms:isPartOf ?pathway .
  ?pathway foaf:page ?page ;
    wp:organismName ?organismName .
  FILTER (?protein1 != ?protein2)
  FILTER {?protein1 a wp:Protein}
  FILTER {?protein2 a wp:Protein}
} ORDER BY ASC(?organism)
