PREFIX wp:    <http://vocabularies.wikipathways.org/wp#>
PREFIX dct:   <http://purl.org/dc/terms/>

SELECT DISTINCT ?pathway ?interaction
WHERE {
   ?wpPathway a wp:Pathway ;
              foaf:page ?pathway .
   ?interaction dcterms:isPartOf ?wpPathway ;
                a wp:Interaction .
   MINUS { ?interaction dct:bibliographicCitation [] }
}
