prefix wp:      <http://vocabularies.wikipathways.org/wp#>
prefix rdfs:    <http://www.w3.org/2000/01/rdf-schema#>
prefix dcterms: <http://purl.org/dc/terms/>
prefix xsd:     <http://www.w3.org/2001/XMLSchema#>

select distinct ?homepage ?label ?identifier 
where {
  ?mb dc:source "HMDB"^^xsd:string ;
    rdfs:label ?label ;
    dcterms:identifier ?identifier ;
    dcterms:isPartOf ?pathway .
  ?pathway foaf:page ?homepage .
  FILTER NOT EXISTS { ?mb a wp:Metabolite }
} order by ?pathway
