prefix dcterms:  <http://purl.org/dc/terms/>
prefix dc:      <http://purl.org/dc/elements/1.1/>
prefix xsd:     <http://www.w3.org/2001/XMLSchema#>
prefix foaf:    <http://xmlns.com/foaf/0.1/>
prefix gpml:  <http://vocabularies.wikipathways.org/gpml#>
prefix wp: <http://vocabularies.wikipathways.org/wp#>

select distinct ?homepage
where {
  ?node gpml:xrefDataSource "Kegg ortholog"^^xsd:string ;
        dcterms:isPartOf ?gpmlpw .
  ?wppw wp:isAbout ?gpmlpw ;
        foaf:page ?homepage .
}
