prefix dcterms:  <http://purl.org/dc/terms/>
prefix dc:      <http://purl.org/dc/elements/1.1/>
prefix xsd:     <http://www.w3.org/2001/XMLSchema#>
prefix foaf:    <http://xmlns.com/foaf/0.1/>
prefix wp:      <http://vocabularies.wikipathways.org/wp#>
prefix gpml:  <http://vocabularies.wikipathways.org/gpml#>

select distinct (str(?idLit) as ?id) ?pathway ?homepage where {
  ?pub a gpml:PublicationXref ;
    gpml:id ?idLit ;
    gpml:database "Pubmed"^^xsd:string .
  ?pub dcterms:isPartOf+/^wp:isAbout ?pathway .
  ?pathway a wp:Pathway ; foaf:page ?homepage .
} ORDER BY ?homepage
