prefix dcterms:  <http://purl.org/dc/terms/>
prefix dc:      <http://purl.org/dc/elements/1.1/>
prefix xsd:     <http://www.w3.org/2001/XMLSchema#>
prefix foaf:    <http://xmlns.com/foaf/0.1/>
prefix wp:      <http://vocabularies.wikipathways.org/wp#>

select distinct ?id ?homepage where {
  ?pub a wp:Interaction ;
    dcterms:identifier ?id ;
    dc:source "Rhea" ;
    dcterms:isPartOf/foaf:page ?homepage .
} ORDER BY ?homepage
