prefix wp:      <http://vocabularies.wikipathways.org/wp#>
prefix rdfs:    <http://www.w3.org/2000/01/rdf-schema#>
prefix dcterms: <http://purl.org/dc/terms/>
prefix foaf:    <http://xmlns.com/foaf/0.1/>
prefix CHEBI:   <https://identifiers.org/chebi/CHEBI:>

select distinct ?homepage ?label ?achiralAA where {
  VALUES ?achiralAA {
    CHEBI:16449 CHEBI:29016 CHEBI:22653 CHEBI:22660 CHEBI:15356 CHEBI:28300
    CHEBI:28300 CHEBI:27570 CHEBI:24898 CHEBI:25017 CHEBI:25094
    CHEBI:16811 CHEBI:28044 CHEBI:26271 CHEBI:17822 CHEBI:26986 CHEBI:27897
    CHEBI:18186 CHEBI:27266
  }
  ?Metabolite a wp:Metabolite ; 
    rdfs:label ?label ;
    dcterms:isPartOf ?pathway ;
    wp:bdbChEBI ?achiralAA .
  ?pathway a wp:Pathway ;
    foaf:page ?homepage .
}