prefix wp:      <http://vocabularies.wikipathways.org/wp#>
prefix gpml:    <http://vocabularies.wikipathways.org/gpml#>

SELECT DISTINCT ?pathway ?metabolite ?label ?id ?type WHERE {
  ?metabolite gpml:xrefDataSource "ChEBI" ; gpml:type ?type ;
    gpml:textlabel ?label .
  MINUS { ?metabolite gpml:type "Metabolite" }
  OPTIONAL { ?metabolite gpml:xrefId ?id . }
  ?gpmlPathway gpml:hasDataNode ?metabolite ; rdfs:seeAlso ?pathway .
}