prefix dcterms: <http://purl.org/dc/terms/>
prefix void:  <http://rdfs.org/ns/void#>
prefix pav:   <http://purl.org/pav/>

select distinct ?date where {
  ?dataset a void:Dataset ;
    dcterms:title ?titleLit ;
    pav:createdOn ?date .
  FILTER (regex(str(?titleLit), "WikiPathways RDF"))
}